name: Deploy to Render

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - main
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Deploy to Render
          if: github.ref == 'refs/heads/main'
          env:
              run: |
                curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
