name: Deploy to Render

on:
    pull_request:
      branches:
        - feature
        - develop
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Deploy to Render
          if: github.ref == 'refs/heads/main'
          run: |
            curl https://api.render.com/deploy/srv-cv6b1abqf0us73f1bue0?key=RBdMvVQB7uY
  
