name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main

jobs:
  cypress-tests:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    name: Run Cypress Component Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress component tests
        run: npx cypress run --component

  deploy-to-render:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-cv6b1abqf0us73f1bue0?key=RBdMvVQB7uY
  

   